language: erlang
notifications:
  recipients:
    - eduardo@gurgel.me
otp_release:
  - R16B
before_install:
  - export MIX_ENV=test
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && git checkout v0.12.0 && make && cd ..
  - export PATH=`pwd`/elixir/bin:$PATH
install: mix deps.get
script: mix test
